### ISSUE TITLE
Panic on starting

### ISSUE THREAD

**Issue by d47zm3** [common-fate/granted#74]
Error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4430458]

goroutine 1 [running]:
github.com/common-fate/granted/pkg/cfaws.(*uninitCFSharedConfig).init(0x46211c0, 0xc000213078)
        /Users/runner/work/granted-cli-build/granted-cli-build/granted/pkg/cfaws/profiles.go:88 +0x18
github.com/common-fate/granted/pkg/cfaws.(*uninitCFSharedConfig).init(0xc000110690, 0xc000213078)
        /Users/runner/work/granted-cli-build/granted-cli-build/granted/pkg/cfaws/profiles.go:98 +0x8e
github.com/common-fate/granted/pkg/cfaws.GetProfilesFromDefaultSharedConfig({0x47c6130, 0xc00019a010})
        /Users/runner/work/granted-cli-build/granted-cli-build/granted/pkg/cfaws/profiles.go:71 +0x169
github.com/common-fate/granted/pkg/assume.AssumeCommand(0xc0001a7a80)
        /Users/runner/work/granted-cli-build/granted-cli-build/granted/pkg/assume/assume.go:28 +0x151
github.com/common-fate/granted/pkg/assume.GetCliApp.func2(0x2)
        /Users/runner/work/granted-cli-build/granted-cli-build/granted/pkg/assume/entrypoint.go:39 +0x19
github.com/common-fate/granted/pkg/updates.WithUpdateCheck.func1(0xc0001a7a80)
        /Users/runner/work/granted-cli-build/granted-cli-build/granted/pkg/updates/updates.go:69 +0x110
github.com/urfave/cli/v2.(*App).RunContext(0xc0002d44e0, {0x47c6130, 0xc00019a010}, {0xc00019c000, 0x2, 0x2})
        /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /Users/runner/work/granted-cli-build/granted-cli-build/granted/cmd/assume/main.go:14 +0x45
```
Version (OS as well)
```
Version: 0.1.5
Darwin xxx 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64 (Big Sur)
```

managed to choose browser (Firefox), installed addon, added shell alias, any calling like `assume <profile or not>` ends up with above.

**Comment by meyerjrr** [comment]
Hey @d47zm3! 
Thanks for using trying out Granted and thanks for the bug report. I have a suspicion that Granted might not be reading your .aws config correctly. Would you be able to give me a look at your config from `~/.aws/config` (minus any sensitive information)?

**Comment by d47zm3** [comment]
Hi @meyerjrr thanks for reaching out, actually my AWS config had 570+ lines so would be hard to paste all of that :) But small example 

```
[default]
region = eu-central-1

[personal]
region = eu-west-1

[profile personal-cicd]
source_profile = personal
role_arn = arn:aws:iam::123456789012:role/AdminAccess

[profile personal-development]
source_profile = personal
role_arn = arn:aws:iam::123456789012:role/AdminAccess

[profile personal-production]
source_profile = personal
role_arn = arn:aws:iam::123456789012:role/AdminAccess

[somecompany]
region = eu-central-1

[company]
region = eu-north-1

[profile company-cicd]
source_profile = company
region = eu-north-1
role_arn = arn:aws:iam::123456789012:role/AdminAccess

[profile company-backups]
source_profile = company
region = eu-north-1
role_arn = arn:aws:iam::123456789012:role/AdminAccess

[profile company-development]
source_profile = company
region = eu-north-1
role_arn = arn:aws:iam::123456789012:role/AdminAccess

[profile project-test]
region = eu-central-1
output = json
source_profile = somecompany
color=4141f4
role_arn = arn:aws:iam::123456789012:role/RestrictedAccesssomecompanyDeveloper

[profile XYZ]
region = eu-central-1
output = json
source_profile = somecompany
color=4141f4
role_arn = arn:aws:iam::123456789012:role/somecompany-devops

[profile ABC]
region = eu-central-1
output = json
source_profile = somecompany
color=4141f4
role_arn = arn:aws:iam::123456789012:role/somecompany-devops
mfa_serial = arn:aws:iam::040229452718:mfa/name.surname

[profile project-stage]
region = eu-central-1
output = json
source_profile = somecompany
color=4141f4
role_arn = arn:aws:iam::123456789012:role/RestrictedAccesssomecompanyDeveloper

[profile project-prod]
region = eu-central-1
output = json
source_profile = somecompany
color=4141f4
role_arn = arn:aws:iam::123456789012:role/RestrictedAccesssomecompanyDeveloper

[profile XXX]
region = eu-west-1
source_profile = somecompany
role_arn = arn:aws:iam::123456789012:role/somecompany-devops
mfa_serial = arn:aws:iam::040229452718:mfa/name.surname
color=16b722

[profile SECRET]
azure_tenant_id = 213-123-123
# Comment
azure_app_id_uri = 55-44-44
azure_default_username = myname@io.com
azure_default_role_arn = arn:aws:iam::123456789012:role/eng
azure_default_duration_hours = 4
azure_default_remember_me = false
region = eu-west-1

[profile admin-role@sensitive-dev-c]
region = eu-west-1
role_arn = arn:aws:iam::123456789012:role/admin-role
source_profile = SECRET

[profile eng@sensitive-dev-c]
region = eu-west-1
role_arn = arn:aws:iam::123456789012:role/eng
source_profile = SECRET

[profile admin-role@SECRET-prd]
region = eu-west-1
role_arn = arn:aws:iam::123456789012:role/admin-role
source_profile = SECRET

[profile eng@SECRET-prd]
region = eu-west-1
role_arn = arn:aws:iam::123456789012:role/eng
source_profile = SECRET

[profile admin-role@SECRET-dev]
region = eu-west-1
role_arn = arn:aws:iam::123456789012:role/admin-role
source_profile = SECRET


...
```

**Comment by jmason** [comment]
I've run into this too. It appears if I replace the "." chars in my profile names with "-" chars, however, it goes away....

**Comment by JoshuaWilkes** [comment]
Thanks @jmason , as it turns out, the AWS go SDK raises an error when "." is in the name of a profile.
In the related PR I have added better warnings when we detect this specific issue, and also made the errors from parsing profiles more accessible.

Previously they only logged when -verbose flag was used, however these errors are crucial to using Granted.
